### ISSUE TITLE
vdr-2.5.1 crash

### ISSUE THREAD

**Issue by 9000h** [rofafor/vdr-plugin-satip#67]
I did try out the new vdr-2.5.1 but I get a crash
```
gdb --args vdr  -l3 -w 60 -P"satip -d2 -s 192.168.178.129|DVBS2-4,DVBC-2,DVBT2-2|minisatip " -P"softhddevice -l3 -f -v va-api -a default -c softvol -w alsa-driver-broken "
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from vdr...
(gdb) r
Starting program: /home/bernd/vdr/vdr/vdr -l3 -w 60 -Psatip\ -d2\ -s\ 192.168.178.129\|DVBS2-4,DVBC-2,DVBT2-2\|minisatip\  -Psofthddevice\ -l3\ -f\ -v\ va-api\ -a\ default\ -c\ softvol\ -w\ alsa-driver-broken\ 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffeb366700 (LWP 60019)]
[New Thread 0x7fffeab65700 (LWP 60020)]
[Thread 0x7fffeb366700 (LWP 60019) exited]
[New Thread 0x7fffeb366700 (LWP 60021)]
[New Thread 0x7fffea161700 (LWP 60022)]
[New Thread 0x7fffe975f700 (LWP 60023)]
[New Thread 0x7fffe8f5e700 (LWP 60024)]
[New Thread 0x7fffd3fff700 (LWP 60025)]
[New Thread 0x7fffd37fe700 (LWP 60026)]
[New Thread 0x7fffd2ffd700 (LWP 60027)]
[New Thread 0x7fffd27fc700 (LWP 60028)]
[New Thread 0x7fffd1003700 (LWP 60029)]
[New Thread 0x7fffd0802700 (LWP 60030)]
[Thread 0x7fffd1003700 (LWP 60029) exited]
[New Thread 0x7fffd1003700 (LWP 60031)]
[Thread 0x7fffd1003700 (LWP 60031) exited]
[New Thread 0x7fffd1003700 (LWP 60032)]
[Thread 0x7fffd1003700 (LWP 60032) exited]
[New Thread 0x7fffd1003700 (LWP 60033)]
[Thread 0x7fffd1003700 (LWP 60033) exited]
[New Thread 0x7fffd1003700 (LWP 60034)]
[Thread 0x7fffd1003700 (LWP 60034) exited]
[New Thread 0x7fffd1003700 (LWP 60035)]
[Thread 0x7fffd1003700 (LWP 60035) exited]
[New Thread 0x7fffd1003700 (LWP 60036)]
[Thread 0x7fffd1003700 (LWP 60036) exited]
[New Thread 0x7fffd1003700 (LWP 60037)]
[Thread 0x7fffd1003700 (LWP 60037) exited]
[New Thread 0x7fffd1003700 (LWP 60038)]
[Thread 0x7fffd1003700 (LWP 60038) exited]
[New Thread 0x7fffd1003700 (LWP 60039)]
[Thread 0x7fffd1003700 (LWP 60039) exited]
[New Thread 0x7fffd1003700 (LWP 60040)]
[Thread 0x7fffd1003700 (LWP 60040) exited]
[New Thread 0x7fffd1003700 (LWP 60041)]
[Thread 0x7fffd1003700 (LWP 60041) exited]
[New Thread 0x7fffd1003700 (LWP 60042)]
[Thread 0x7fffd1003700 (LWP 60042) exited]
[New Thread 0x7fffd1003700 (LWP 60043)]
[Thread 0x7fffd1003700 (LWP 60043) exited]
[New Thread 0x7fffd1003700 (LWP 60044)]
[Thread 0x7fffd1003700 (LWP 60044) exited]
[New Thread 0x7fffd1003700 (LWP 60045)]
[Thread 0x7fffd1003700 (LWP 60045) exited]
[New Thread 0x7fffd1003700 (LWP 60046)]
[Thread 0x7fffd1003700 (LWP 60046) exited]
[New Thread 0x7fffd1003700 (LWP 60047)]
[Thread 0x7fffd1003700 (LWP 60047) exited]
[New Thread 0x7fffd1003700 (LWP 60048)]
[Thread 0x7fffd1003700 (LWP 60048) exited]
[New Thread 0x7fffd1003700 (LWP 60049)]
[Thread 0x7fffd1003700 (LWP 60049) exited]
[New Thread 0x7fffd1003700 (LWP 60050)]
[Thread 0x7fffd1003700 (LWP 60050) exited]
[New Thread 0x7fffd1003700 (LWP 60051)]
[Thread 0x7fffd1003700 (LWP 60051) exited]
[New Thread 0x7fffd1003700 (LWP 60052)]
[Thread 0x7fffd1003700 (LWP 60052) exited]
[New Thread 0x7fffd1003700 (LWP 60053)]
[Thread 0x7fffd1003700 (LWP 60053) exited]
[New Thread 0x7fffd1003700 (LWP 60054)]
[New Thread 0x7fff97fff700 (LWP 60055)]
[New Thread 0x7fff8ad13700 (LWP 60056)]
[Thread 0x7fffeab65700 (LWP 60020) exited]
--Type <RET> for more, q to quit, c to continue without paging--c

Thread 1 "vdr" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:262
262	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:262
#1  0x000055555568d2eb in memcpy (__len=2096952, __src=0x2, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34
#2  cRingBufferLinear::Put(unsigned char const*, int) (this=0x5555557c1060, Data=Data@entry=0x2 <error: Cannot access memory at address 0x2>, Count=2096952, Count@entry=1432441152) at ringbuffer.c:329
#3  0x00007ffff7155ccc in cSatipSectionFilterHandler::Write(unsigned char*, int) (this=0x555555e90f40, bufferP=0x2 <error: Cannot access memory at address 0x2>, lengthP=1432441152) at sectionfilter.c:456
#4  0x0000555555616057 in cDevice::GetDevice(cChannel const*, int, bool, bool) (Channel=0x5555558de030, Priority=<optimized out>, LiveView=<optimized out>, Query=<optimized out>) at device.c:356
#5  0x000055555561822a in cDevice::SetChannel(cChannel const*, bool) (this=0x555555ed4480, Channel=0x5555558de030, LiveView=<optimized out>) at device.c:881
#6  0x000055555561836a in cDevice::SwitchChannel(cChannel const*, bool) (this=0x555555ed4480, Channel=0x5555558de030, LiveView=<optimized out>) at device.c:809
#7  0x00005555555f59a8 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at vdr.c:927
(gdb) 
```
any ideas how to fix ?

**Comment by 9000h** [comment]
probably my fault and compiled with old headers
